CREATE WAREHOUSE IF NOT EXISTS  RETAIL_PULSE_WH ; 
CREATE DATABASE IF NOT EXISTS RETAIL_PULSE_DB ; 
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE_DB.BRONZE ; 
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE_DB.GOLD ; 
CREATE SCHEMA IF NOT EXISTS RETAIL_PULSE_DB.SILVER ; 
