-- Section 1 : accès en lecture SR 
-- 1. Accès a la base de données 
GRANT USAGE ON DATABASE RETAIL_PULSE_DB TO ROLE RETAIL_PULSE_GOLD_SR ; 
GRANT USAGE ON DATABASE RETAIL_PULSE_DB TO ROLE RETAIL_PULSE_SILVER_SR ; 
GRANT USAGE ON DATABASE RETAIL_PULSE_DB TO ROLE RETAIL_PULSE_BRONZE_SR ; 

-- 2.Accès au schema 
GRANT USAGE ON SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SR ; 
GRANT USAGE ON SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SR ; 
GRANT USAGE ON SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SR ; 

-- 3.lECTURE SUR LES TABLES ET LES VUES EXISTANTES
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SR; 
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SR; 
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SR; 
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SR; 
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SR; 
GRANT SELECT ON ALL VIEWS IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SR; 

-- 4. Lecture des tables et vues qui seront crées dans le futur 
GRANT SELECT ON  FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SR; 
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SR ;
GRANT SELECT ON  FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SR; 
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SR ;
GRANT SELECT ON  FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SR; 
GRANT SELECT ON  FUTURE VIEWS IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SR ;

-- Section 2 : accès en écriture SW
-- 1. Accès a la base de données 
GRANT USAGE ON DATABASE RETAIL_PULSE_DB TO ROLE RETAIL_PULSE_GOLD_SW ; 
GRANT USAGE ON DATABASE RETAIL_PULSE_DB TO ROLE RETAIL_PULSE_SILVER_SW ; 
GRANT USAGE ON DATABASE RETAIL_PULSE_DB TO ROLE RETAIL_PULSE_BRONZE_SW ; 

-- 2.Accès au schema 
GRANT USAGE ON SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SW ; 
GRANT USAGE ON SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SW ; 
GRANT USAGE ON SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SW ; 

-- 3.Ecriture SUR LES TABLES EXISTANTES
GRANT INSERT , UPDATE , DELETE ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SW;  
GRANT INSERT , UPDATE , DELETE ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SW; 
GRANT INSERT , UPDATE , DELETE ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SW; 


-- 4. Ecriture des tables qui seront crées dans le futur 
GRANT INSERT , UPDATE , DELETE ON FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SW; 
GRANT INSERT , UPDATE , DELETE ON FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SW; 
GRANT INSERT , UPDATE , DELETE ON FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SW; 


-- Section 3 : accès COMPLET SFULL 
-- 1. lE ROLE SFULL hérite des roles sr et sw 
GRANT ROLE RETAIL_PULSE_GOLD_SR TO ROLE RETAIL_PULSE_GOLD_SFULL ; 
GRANT ROLE RETAIL_PULSE_GOLD_SW TO ROLE RETAIL_PULSE_GOLD_SFULL ; 
GRANT ROLE RETAIL_PULSE_SILVER_SR TO ROLE RETAIL_PULSE_SILVER_SFULL ; 
GRANT ROLE RETAIL_PULSE_SILVER_SW TO ROLE RETAIL_PULSE_SILVER_SFULL ; 
GRANT ROLE RETAIL_PULSE_BRONZE_SR TO ROLE RETAIL_PULSE_BRONZE_SFULL ; 
GRANT ROLE RETAIL_PULSE_BRONZE_SW TO ROLE RETAIL_PULSE_BRONZE_SFULL ; 

-- 2. Créer des tables et des vues 
GRANT CREATE TABLE , CREATE VIEW ON SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SFULL ; 
GRANT CREATE TABLE , CREATE VIEW ON SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SFULL ; 
GRANT CREATE TABLE , CREATE VIEW ON SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SFULL ; 

-- 3. Vider les tables existantes 
GRANT TRUNCATE ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SFULL ; 
GRANT TRUNCATE ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SFULL ; 
GRANT TRUNCATE ON ALL TABLES IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SFULL ; 

-- 4. Vider les tables futures 
GRANT TRUNCATE ON  FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.GOLD TO ROLE RETAIL_PULSE_GOLD_SFULL ; 
GRANT TRUNCATE ON  FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.SILVER TO ROLE RETAIL_PULSE_SILVER_SFULL ; 
GRANT TRUNCATE ON  FUTURE TABLES IN SCHEMA RETAIL_PULSE_DB.BRONZE TO ROLE RETAIL_PULSE_BRONZE_SFULL ; 



SHOW GRANTS TO ROLE RETAIL_PULSE_GOLD_SW; -- attribue les droits aux tables qui existent au moment où tu exécutes la commande. Tes schémas étant vides, rien n’apparaît encore pour ces tables.
SHOW FUTURE GRANTS TO ROLE RETAIL_PULSE_GOLD_SW; -- prépare les droits pour les tables qui seront créées plus tard.

