GRANT ROLE RETAIL_PULSE_GOLD_SR TO ROLE RETAIL_DATA_ANALYST ; 
GRANT ROLE RETAIL_PULSE_SILVER_SR TO ROLE RETAIL_DATA_ANALYST; 

GRANT USAGE ON WAREHOUSE RETAIL_PULSE_WH TO ROLE RETAIL_DATA_ANALYST ; 

GRANT ROLE RETAIL_DATA_ANALYST TO USER STEPH242 ; 
