COPY INTO RETAIL_PULSE_DB.BRONZE.BRZ_TRANSACTIONS
FROM @RETAIL_PULSE_DB.BRONZE.STG_TRANSACTIONS_INTERNAL
FILES = ('transactions_internal.json.gz')
FILE_FORMAT =(
    FORMAT_NAME= 'RETAIL_PULSE_DB.BRONZE.JSON_TRANSACTION_FORMAT'
) ; 

