CREATE TASK RETAIL_PULSE_DB.SILVER.TSK_CAPTURE_TRANSACTIONS
    WAREHOUSE = RETAIL_PULSE_WH
    SCHEDULE = '1 HOUR'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'RETAIL_PULSE_DB.BRONZE.STR_BRZ_TRANSACTIONS'
    )
AS
    INSERT INTO RETAIL_PULSE_DB.SILVER.TRANSACTION_DELTA (RAW_DATA)
    SELECT RAW_DATA
    FROM RETAIL_PULSE_DB.BRONZE.STR_BRZ_TRANSACTIONS;