CREATE TASK RETAIL_PULSE_DB.SILVER.TSK_BUILD_FACT_SALES
    WAREHOUSE = RETAIL_PULSE_WH
    AFTER RETAIL_PULSE_DB.SILVER.TSK_CAPTURE_TRANSACTIONS
AS
    EXECUTE DBT PROJECT RETAIL_PULSE_DB.SILVER.RETAIL_PULSE_DBT
        ARGS = 'run --select fact_sales';