SELECT *
FROM RETAIL_PULSE_DB.SILVER.SLV_TRANSACTIONS
LIMIT 10;

INSERT INTO RETAIL_PULSE_DB.BRONZE.BRZ_TRANSACTIONS (RAW_DATA)
SELECT PARSE_JSON('{
  "transaction_id": "TX-CDC-TEST-20261006-001",
  "customer_info": {
    "id": "C-CDC-001",
    "email": "test.cdc@example.com",
    "country": " fr "
  },
  "items": [
    {"product_id": "P-101", "quantity": 1, "unit_price": 12.50},
    {"product_id": "P-202", "quantity": 2, "unit_price": 15.00}
  ],
  "total_amount": 42.50,
  "event_timestamp": "2026-10-06T16:40:00Z"
}');

SELECT
    RAW_DATA:transaction_id::STRING AS transaction_id,
    METADATA$ACTION AS action
FROM RETAIL_PULSE_DB.BRONZE.STR_BRZ_TRANSACTIONS
WHERE RAW_DATA:transaction_id::STRING = 'TX-CDC-TEST-20261006-001';

SELECT TRANSACTION_ID, TOTAL_AMOUNT
FROM RETAIL_PULSE_DB_DEV.GOLD.FACT_SALES
LIMIT 5;

UPDATE RETAIL_PULSE_DB_DEV.GOLD.FACT_SALES
SET TOTAL_AMOUNT = TOTAL_AMOUNT + 10
WHERE TRANSACTION_ID = 'TX-000501';

SELECT LAST_QUERY_ID() AS UPDATE_QUERY_ID;

-- Valeur juste avant la mise à jour
SELECT TRANSACTION_ID, TOTAL_AMOUNT
FROM RETAIL_PULSE_DB_DEV.GOLD.FACT_SALES
    BEFORE (STATEMENT => '01c78d76-0000-a676-0001-2d220004758e')
WHERE TRANSACTION_ID = 'TX-000501';

-- Valeur après la mise à jour
SELECT TRANSACTION_ID, TOTAL_AMOUNT
FROM RETAIL_PULSE_DB_DEV.GOLD.FACT_SALES
    AT (STATEMENT => '01c78d76-0000-a676-0001-2d220004758e')
WHERE TRANSACTION_ID = 'TX-000501';

SHOW TASKS IN SCHEMA RETAIL_PULSE_DB.SILVER;

-- lancer les tasks sur started
ALTER TASK RETAIL_PULSE_DB.SILVER.TSK_BUILD_FACT_SALES RESUME;

ALTER TASK RETAIL_PULSE_DB.SILVER.TSK_CAPTURE_TRANSACTIONS RESUME;




